"""
Utility functions for loading JWT RSA keys from environment variables or files.
"""
import os
import logging
from django.conf import settings

logger = logging.getLogger(__name__)


def get_rsa_public_key():
    """
    Get RSA public key from environment variable or file.
    
    Priority:
    1. JWT_RSA_PUBLIC_KEY_FILE (file path)
    2. JWT_RSA_PUBLIC_KEY (direct key content)
    3. Fallback to hardcoded key (for backward compatibility, with warning)
    
    Returns:
        str: RSA public key in PEM format, or None if not found
    """
    # Try file path first
    key_file = getattr(settings, 'JWT_RSA_PUBLIC_KEY_FILE', None)
    if key_file and os.path.exists(key_file):
        try:
            with open(key_file, 'r') as f:
                key = f.read().strip()
                logger.info(f"Loaded RSA public key from file: {key_file}")
                return key
        except Exception as e:
            logger.error(f"Error reading RSA public key file {key_file}: {e}")
    
    # Try direct key content from environment
    key_content = getattr(settings, 'JWT_RSA_PUBLIC_KEY', None)
    if key_content:
        logger.info("Loaded RSA public key from environment variable")
        return key_content
    
    # Fallback to hardcoded key (for backward compatibility)
    # This should be removed in production
    fallback_key = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiaGItq0JK2JxMf66rTqF
efn6jVWcpFOn9y7c5eFJM4+FFrr0yFGtcH9DevSYP8nREFYEpTnJckILK1AHDiZl
9KUh3nQTUW1ZKnlT6WLSgUjTc2AiT5kpe5HU9Fq8hL4VL4hEcCnWcdhQZA+/gEnh
R/98OUwGnWgWeai0noLaI53bthm8vyBz2G6VxQ52ZVhfuOmxTHeXvHTWciDUO81/
NInA+iyiuOOP/U4yQP1eFbwyDZA6Tvn9P2Tx5b+FF4azYYjl/BHCEoJNeHGRwRDw
ErY3serZYpd4vzHlWjnrSFV1yTQ8K8DtFMbefpE4A4VpHFFvKlx8r574rNVxBz+p
5wIDAQAB
-----END PUBLIC KEY-----"""
    
    logger.warning(
        "Using hardcoded RSA public key. "
        "Set JWT_RSA_PUBLIC_KEY or JWT_RSA_PUBLIC_KEY_FILE environment variable for production!"
    )
    return fallback_key


def get_rsa_private_key():
    """
    Get RSA private key from environment variable or file.
    
    WARNING: Private keys should only be used for token generation in development/testing.
    In production, tokens should be generated by the OAuth provider (portbro.com).
    
    Priority:
    1. JWT_RSA_PRIVATE_KEY_FILE (file path)
    2. JWT_RSA_PRIVATE_KEY (direct key content)
    3. None (no fallback for security)
    
    Returns:
        str: RSA private key in PEM format, or None if not found
    """
    # Try file path first
    key_file = getattr(settings, 'JWT_RSA_PRIVATE_KEY_FILE', None)
    if key_file and os.path.exists(key_file):
        try:
            with open(key_file, 'r') as f:
                key = f.read().strip()
                logger.info(f"Loaded RSA private key from file: {key_file}")
                return key
        except Exception as e:
            logger.error(f"Error reading RSA private key file {key_file}: {e}")
    
    # Try direct key content from environment
    key_content = getattr(settings, 'JWT_RSA_PRIVATE_KEY', None)
    if key_content:
        logger.info("Loaded RSA private key from environment variable")
        return key_content
    
    # No fallback for private keys - return None
    logger.warning("RSA private key not found. Token generation will not work.")
    return None
