# Generated by Django 5.2 on 2025-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0007_alter_useracl_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
