# Generated by Django 5.1.4 on 2025-09-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0027_alter_wireguardinstance_peer_list_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardinstance',
            name='allow_peer_to_peer',
            field=models.BooleanField(default=True, help_text='Allow peers within this instance to communicate with each other'),
        ),
    ]
