# Generated by Django 5.1.4 on 2025-09-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0028_wireguardinstance_allow_peer_to_peer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wireguardinstance',
            name='allow_peer_to_peer',
        ),
    ]
