# Generated by Django 5.1.4 on 2025-09-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0029_remove_wireguardinstance_allow_peer_to_peer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardinstance',
            name='bandwidth_limit_enabled',
            field=models.BooleanField(default=True, help_text='Enable bandwidth limiting for this instance'),
        ),
        migrations.AddField(
            model_name='wireguardinstance',
            name='bandwidth_limit_mbps',
            field=models.PositiveIntegerField(default=50, help_text='Bandwidth limit in Mbps'),
        ),
    ]
