# Generated by Django 4.2.24 on 2025-09-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0030_wireguardinstance_bandwidth_limit_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='hostname',
            field=models.CharField(blank=True, help_text="DNS hostname for this peer (e.g., 'laptop', 'server')", max_length=100, null=True),
        ),
    ]
