# Generated by Django 4.2.24 on 2025-09-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0031_add_peer_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireguardinstance',
            name='dns_primary',
            field=models.GenericIPAddressField(blank=True, default='172.19.0.2', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='wireguardinstance',
            name='dns_secondary',
            field=models.GenericIPAddressField(blank=True, default='8.8.8.8', null=True, protocol='IPv4'),
        ),
    ]
