# Generated by Django 5.2.2 on 2025-06-05 20:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('user_count', models.IntegerField(default=1)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
